spring:
  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:localhost:9092}
    value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      client-id: kafka-message-producer
      acks: all
      value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      group-id: ${consumer.group:group}
    topic:
      book-status: book-status
      book-availability: book-availability

  data:
    mongodb:
      authentication-database: inventory
      host: ${mongodb.host:localhost}
      port: ${mongodb.port:28017}
      username: ${mongodb.user:root}
      password: ${mongodb.password:root1}
      database: inventory

mongock:
  change-logs-scan-package: com.productdock.library.inventory.config.dbmigrations

logging:
  level:
    com.productdock.library.inventory: ${logging.level:INFO}