KAFKA_SERVER_URL: localhost:9093
USER_PROFILES_JWT_PUBLIC_KEY: src/main/resources/app-local.pub
CATALOG_SERVICE_URL: http://localhost:8082
MONGO_SERVER_URL: localhost
MONGO_SERVER_PORT: 28017
MONGO_USERNAME: root
MONGO_PASSWORD: root1

LOG_TO_FILE: false